spring.application.name=event-manager

spring.datasource.url=jdbc:postgresql://localhost:5432/event-manager-db
spring.datasource.username=postgres
spring.datasource.password=zhopa
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#springdoc.swagger-ui.url: /openapi.yaml

logging.level.root=INFO

logging.level.org.springframework.security=DEBUG

spring.output.ansi.enabled=ALWAYS

jwt.lifetime = 86400000
jwt.secret-key = D19BBDA8BA9262208E2D2238F06A1DA0639F62179939A7164AEA3F480C2FE00F
